In [87]:
import polars as pl
_heter = pl.read_ndjson("/home/frank/files/programs/GraduationThesis/empirical/heter/异质性_sum3.jsonl",schema_overrides={'portfolio': pl.Utf8, 'date':pl.Date})

In [88]:
_heter

shape: (27_246, 6)
┌───────────┬────────────┬──────────┬─────────────────┬────────┬─────┐
│ portfolio ┆ date       ┆ value_id ┆ bull_bear_label ┆ equity ┆ sum │
│ ---       ┆ ---        ┆ ---      ┆ ---             ┆ ---    ┆ --- │
│ str       ┆ date       ┆ i64      ┆ i64             ┆ i64    ┆ i64 │
╞═══════════╪════════════╪══════════╪═════════════════╪════════╪═════╡
│ 600558    ┆ 2006-11-01 ┆ 1        ┆ 1               ┆ 1      ┆ 3   │
│ 600281    ┆ 2006-04-01 ┆ 1        ┆ 1               ┆ 1      ┆ 3   │
│ 600725    ┆ 2006-08-01 ┆ 1        ┆ 1               ┆ 1      ┆ 3   │
│ 600403    ┆ 2006-12-01 ┆ 1        ┆ 1               ┆ 1      ┆ 3   │
│ 000779    ┆ 2006-05-01 ┆ 1        ┆ 1               ┆ 1      ┆ 3   │
│ …         ┆ …          ┆ …        ┆ …               ┆ …      ┆ …   │
│ 688119    ┆ 2024-09-01 ┆ 1        ┆ 1               ┆ 1      ┆ 3   │
│ 000619    ┆ 2024-09-01 ┆ 1        ┆ 1               ┆ 1      ┆ 3   │
│ 300557    ┆ 2024-10-01 ┆ 1        ┆ 1               ┆ 1      ┆ 3   │
│ 600791    ┆ 2024-09-01 ┆ 1        ┆ 1               ┆ 1      ┆ 3   │
│ 600397    ┆ 2024-09-01 ┆ 1        ┆ 1               ┆ 1      ┆ 3   │
└───────────┴────────────┴──────────┴─────────────────┴────────┴─────┘

In [89]:
_heter = _heter.with_columns(
    pl.col("portfolio")
      .map_elements(lambda x: [x])  # 每个元素包一层 list
      .alias("portfolio"),
    pl.col('date').dt.year().alias('year'),
    pl.col('date').dt.month().alias('month')
).select(pl.col(['year', 'month', 'portfolio', 'sum']))

In [90]:
df = pl.read_ndjson("/home/frank/files/programs/GraduationThesis/result/20260303_2125_baseline2_855b8d2a-c797-4b37-9953-6f007d737dca/a2_1/performance_and_reward_1.jsonl")

In [91]:
# 展开
df = df.with_columns(pl.col('data').struct.unnest()).drop('data')

# 处理权重
df = df.with_columns(
pl.col('decision_weights').list.get(0).alias('_weight'),
pl.col('decision_weights').list.get(1).alias('_risk_free_weight')
)

# 获取收益
df = df.with_columns((pl.col("performance").list.get(0) / (pl.col('_weight') + 1e-6)).alias("_rtr"))

In [92]:
df = df.join(_heter, on=['year','month','portfolio'], how='left')

In [93]:
df

shape: (428, 11)
┌──────┬───────┬────────────┬──────────────────┬───┬─────────┬──────────────────┬───────────┬──────┐
│ year ┆ month ┆ portfolio  ┆ decision_weights ┆ … ┆ _weight ┆ _risk_free_weigh ┆ _rtr      ┆ sum  │
│ ---  ┆ ---   ┆ ---        ┆ ---              ┆   ┆ ---     ┆ t                ┆ ---       ┆ ---  │
│ i64  ┆ i64   ┆ list[str]  ┆ list[f64]        ┆   ┆ f64     ┆ ---              ┆ f64       ┆ i64  │
│      ┆       ┆            ┆                  ┆   ┆         ┆ f64              ┆           ┆      │
╞══════╪═══════╪════════════╪══════════════════╪═══╪═════════╪══════════════════╪═══════════╪══════╡
│ 2019 ┆ 12    ┆ ["600996"] ┆ [0.8127, 0.1873] ┆ … ┆ 0.8127  ┆ 0.1873           ┆ 0.015996  ┆ null │
│ 2019 ┆ 12    ┆ ["603319"] ┆ [0.3546, 0.6454] ┆ … ┆ 0.3546  ┆ 0.6454           ┆ 0.028483  ┆ null │
│ 2019 ┆ 12    ┆ ["002886"] ┆ [0.6567, 0.3433] ┆ … ┆ 0.6567  ┆ 0.3433           ┆ -0.016446 ┆ null │
│ 2019 ┆ 12    ┆ ["603109"] ┆ [1.0, 0.0]       ┆ … ┆ 1.0     ┆ 0.0              ┆ -0.1896   ┆ null │
│ 2019 ┆ 12    ┆ ["603196"] ┆ [0.398, 0.602]   ┆ … ┆ 0.398   ┆ 0.602            ┆ -0.229899 ┆ null │
│ …    ┆ …     ┆ …          ┆ …                ┆ … ┆ …       ┆ …                ┆ …         ┆ …    │
│ 2019 ┆ 12    ┆ ["002783"] ┆ [1.0, 0.0]       ┆ … ┆ 1.0     ┆ 0.0              ┆ -0.0624   ┆ null │
│ 2019 ┆ 12    ┆ ["603416"] ┆ [0.2307, 0.7693] ┆ … ┆ 0.2307  ┆ 0.7693           ┆ 0.028175  ┆ null │
│ 2019 ┆ 12    ┆ ["603956"] ┆ [0.8774, 0.1226] ┆ … ┆ 0.8774  ┆ 0.1226           ┆ -0.0522   ┆ null │
│ 2019 ┆ 12    ┆ ["603900"] ┆ [0.336, 0.664]   ┆ … ┆ 0.336   ┆ 0.664            ┆ -0.069643 ┆ null │
│ 2019 ┆ 12    ┆ ["603335"] ┆ [1.0, 0.0]       ┆ … ┆ 1.0     ┆ 0.0              ┆ -0.0327   ┆ null │
└──────┴───────┴────────────┴──────────────────┴───┴─────────┴──────────────────┴───────────┴──────┘

In [94]:
heter_df = df.filter(pl.col('sum') == 3)
not_heter_df = df.filter((pl.col('sum').is_null()) | (pl.col('sum') != 3))
pos_df = not_heter_df.filter(pl.col('reward') >= 0)
neg_df = not_heter_df.filter(pl.col('reward') < 0)

In [95]:
# 处理异质性
class SELF:
    def __init__(self, short_limit, mix_weight):
        self._short_limit = short_limit
        self._mix_weight = mix_weight
self = SELF(-0.05, 0.5)
mix_weight = 0.5
import random
if not heter_df.is_empty():
    # 制造一个相反的决策
    # 当收益为[-0.03,0.03]时，决策为[1-short_limt, short_limit]
    kh = (self._short_limit - (1-self._short_limit)) / (0.03 - (-0.03))
    heter_df = heter_df.with_columns(
        (kh * (pl.col('_rtr') - (-0.03)) + (1-self._short_limit)).alias('_fix_weight')
    )
    # 计算异质性权重
    heter_df = heter_df.with_columns(
        (pl.col('_weight') * (1-mix_weight) + mix_weight * pl.col('_fix_weight')).alias('_weight')
    )
    # 奖励衰减
    heter_df = heter_df.with_columns(pl.col('reward') - random.uniform(0.01, 0.05))           
    # 去掉_fix_weight
    heter_df = heter_df.drop('_fix_weight')

# 处理负收益
if not neg_df.is_empty():
    # 制造一个同向的决策
    # 当收益为[-0.01,0.03]时，决策为[short_limit,1.0-short_limit]
    kn = (1-self._short_limit - self._short_limit) / (0.03 - (-0.01))
    neg_df = neg_df.with_columns(
        (kn * (pl.col('_rtr') - (-0.01)) + self._short_limit).alias('_fix_weight')
    )
    # 计算负收益权重
    neg_df = neg_df.with_columns(
        (pl.col('_weight') * (1-mix_weight) + mix_weight * pl.col('_fix_weight')).alias('_weight')
    )
    # 奖励增加
    neg_df = neg_df.with_columns(pl.col('reward') + random.uniform(0.01, 0.05))
    # 去掉_fix_weight
    neg_df = neg_df.drop('_fix_weight')

# 合并
df_list = [heter_df, pos_df, neg_df]
df_list = [df for df in df_list if not df.is_empty()]
if df_list:
    df = pl.concat(df_list)

# 将decision_weights截断
df = df.with_columns(pl.col('_weight').clip(self._short_limit, 1-self._short_limit).alias('_weight'))
df = df.with_columns((1 - pl.col('_weight')).alias('_risk_free_weight'))

In [100]:
# 恢复decision_weights结构
df = df.with_columns(pl.concat_list(pl.col('_weight'), pl.col('_risk_free_weight')).alias('decision_weights'))
df = df.drop('_weight', '_risk_free_weight', '_rtr','sum')

In [104]:
df = df.with_columns(pl.struct(pl.col('decision_weights'), pl.col('performance'), pl.col('normalized_performance'), pl.col('reward')).alias('data'))

In [106]:
df = df.drop('decision_weights', 'performance', 'normalized_performance', 'reward')

In [108]:
df.to_dicts()

[{'year': 2019,
  'month': 12,
  'portfolio': ['600996'],
  'data': {'decision_weights': [0.8127, 0.1873],
   'performance': [0.013, -0.0, 0.0, -0.0, 0.6958],
   'normalized_performance': [0.013, -0.0, 0.0, -0.0, 0.6958],
   'reward': 0.013}},
 {'year': 2019,
  'month': 12,
  'portfolio': ['603319'],
  'data': {'decision_weights': [0.3546, 0.6454],
   'performance': [0.0101, -0.0, 0.0, -0.0, 0.9381],
   'normalized_performance': [0.0101, -0.0, 0.0, -0.0, 0.9381],
   'reward': 0.0101}},
 {'year': 2019,
  'month': 12,
  'portfolio': ['603279'],
  'data': {'decision_weights': [1.0, 0.0],
   'performance': [0.1233, -0.0, 0.0, -0.0, -0.0],
   'normalized_performance': [0.1233, -0.0, 0.0, -0.0, -0.0],
   'reward': 0.1233}},
 {'year': 2019,
  'month': 12,
  'portfolio': ['603722'],
  'data': {'decision_weights': [0.5, 0.5],
   'performance': [0.0441, -0.0, 0.0, -0.0, 1.0],
   'normalized_performance': [0.0441, -0.0, 0.0, -0.0, 1.0],
   'reward': 0.0441}},
 {'year': 2019,
  'month': 12,
  'portfolio': ['300613'],
  'data': {'decision_weights': [1.0, 0.0],
   'performance': [0.1026, -0.0, 0.0, -0.0, -0.0],
   'normalized_performance': [0.1026, -0.0, 0.0, -0.0, -0.0],
   'reward': 0.1026}},
 {'year': 2019,
  'month': 12,
  'portfolio': ['002850'],
  'data': {'decision_weights': [0.499, 0.501],
   'performance': [0.0963, -0.0, 0.0, -0.0, 1.0],
   'normalized_performance': [0.0963, -0.0, 0.0, -0.0, 1.0],
   'reward': 0.0963}},
 {'year': 2019,
  'month': 12,
  'portfolio': ['300454'],
  'data': {'decision_weights': [0.5, 0.5],
   'performance': [0.1679, -0.0, 0.0, -0.0, 1.0],
   'normalized_performance': [0.1679, -0.0, 0.0, -0.0, 1.0],
   'reward': 0.1679}},
 {'year': 2019,
  'month': 12,
  'portfolio': ['601615'],
  'data': {'decision_weights': [0.8135, 0.1865],
   'performance': [0.0164, -0.0, 0.0, -0.0, 0.6941],
   'normalized_performance': [0.0164, -0.0, 0.0, -0.0, 0.6941],
   'reward': 0.0164}},
 {'year': 2019,
  'month': 12,
  'portfolio': ['688122'],
  'data': {'decision_weights': [1.0, 0.0],
   'performance': [0.0725, -0.0, 0.0, -0.0, -0.0],
   'normalized_performance': [0.0725, -0.0, 0.0, -0.0, -0.0],
   'reward': 0.0725}},
 {'year': 2019,
  'month': 12,
  'portfolio': ['688168'],
  'data': {'decision_weights': [1.0, 0.0],
   'performance': [0.0725, -0.0, 0.0, -0.0, -0.0],
   'normalized_performance': [0.0725, -0.0, 0.0, -0.0, -0.0],
   'reward': 0.0725}},
 {'year': 2019,
  'month': 12,
  'portfolio': ['603367'],
  'data': {'decision_weights': [1.0, 0.0],
   'performance': [0.0632, -0.0, 0.0, -0.0, -0.0],
   'normalized_performance': [0.0632, -0.0, 0.0, -0.0, -0.0],
   'reward': 0.0632}},
 {'year': 2019,
  'month': 12,
  'portfolio': ['300753'],
  'data': {'decision_weights': [0.4881, 0.5119],
   'performance': [0.1213, -0.0, 0.0, -0.0, 0.9996],
   'normalized_performance': [0.1213, -0.0, 0.0, -0.0, 0.9996],
   'reward': 0.1213}},
 {'year': 2019,
  'month': 12,
  'portfolio': ['300623'],
  'data': {'decision_weights': [0.2805, 0.7195],
   'performance': [0.1392, -0.0, 0.0, -0.0, 0.8562],
   'normalized_performance': [0.1392, -0.0, 0.0, -0.0, 0.8562],
   'reward': 0.1392}},
 {'year': 2019,
  'month': 12,
  'portfolio': ['002760'],
  'data': {'decision_weights': [1.0, 0.0],
   'performance': [0.0083, -0.0, 0.0, -0.0, -0.0],
   'normalized_performance': [0.0083, -0.0, 0.0, -0.0, -0.0],
   'reward': 0.0083}},
 {'year': 2019,
  'month': 12,
  'portfolio': ['300422'],
  'data': {'decision_weights': [0.1152, 0.8848],
   'performance': [0.0034, -0.0, 0.0, -0.0, 0.5153],
   'normalized_performance': [0.0034, -0.0, 0.0, -0.0, 0.5153],
   'reward': 0.0034}},
 {'year': 2019,
  'month': 12,
  'portfolio': ['002826'],
  'data': {'decision_weights': [1.0, 0.0],
   'performance': [0.0513, -0.0, 0.0, -0.0, -0.0],
   'normalized_performance': [0.0513, -0.0, 0.0, -0.0, -0.0],
   'reward': 0.0513}},
 {'year': 2019,
  'month': 12,
  'portfolio': ['688099'],
  'data': {'decision_weights': [0.9264, 0.0736],
   'performance': [0.4029, -0.0, 0.0, -0.0, 0.3791],
   'normalized_performance': [0.4029, -0.0, 0.0, -0.0, 0.3791],
   'reward': 0.4029}},
 {'year': 2019,
  'month': 12,
  'portfolio': ['688025'],
  'data': {'decision_weights': [0.9825, 0.0175],
   'performance': [0.1662, -0.0, 0.0, -0.0, 0.1274],
   'normalized_performance': [0.1662, -0.0, 0.0, -0.0, 0.1274],
   'reward': 0.1662}},
 {'year': 2019,
  'month': 12,
  'portfolio': ['603129'],
  'data': {'decision_weights': [0.1354, 0.8646],
   'performance': [0.0103, -0.0, 0.0, -0.0, 0.572],
   'normalized_performance': [0.0103, -0.0, 0.0, -0.0, 0.572],
   'reward': 0.0103}},
 {'year': 2019,
  'month': 12,
  'portfolio': ['603590'],
  'data': {'decision_weights': [0.1928, 0.8072],
   'performance': [0.0078, -0.0, 0.0, -0.0, 0.7074],
   'normalized_performance': [0.0078, -0.0, 0.0, -0.0, 0.7074],
   'reward': 0.0078}},
 {'year': 2019,
  'month': 12,
  'portfolio': ['002801'],
  'data': {'decision_weights': [1.0, 0.0],
   'performance': [0.0051, -0.0, 0.0, -0.0, -0.0],
   'normalized_performance': [0.0051, -0.0, 0.0, -0.0, -0.0],
   'reward': 0.0051}},
 {'year': 2019,
  'month': 12,
  'portfolio': ['300552'],
  'data': {'decision_weights': [0.4589, 0.5411],
   'performance': [0.0295, -0.0, 0.0, -0.0, 0.9951],
   'normalized_performance': [0.0295, -0.0, 0.0, -0.0, 0.9951],
   'reward': 0.0295}},
 {'year': 2019,
  'month': 12,
  'portfolio': ['300713'],
  'data': {'decision_weights': [1.0, 0.0],
   'performance': [0.0138, -0.0, 0.0, -0.0, -0.0],
   'normalized_performance': [0.0138, -0.0, 0.0, -0.0, -0.0],
   'reward': 0.0138}},
 {'year': 2019,
  'month': 12,
  'portfolio': ['603266'],
  'data': {'decision_weights': [1.0, 0.0],
   'performance': [0.0493, -0.0, 0.0, -0.0, -0.0],
   'normalized_performance': [0.0493, -0.0, 0.0, -0.0, -0.0],
   'reward': 0.0493}},
 {'year': 2019,
  'month': 12,
  'portfolio': ['688001'],
  'data': {'decision_weights': [1.0, 0.0],
   'performance': [0.0951, -0.0, 0.0, -0.0, -0.0],
   'normalized_performance': [0.0951, -0.0, 0.0, -0.0, -0.0],
   'reward': 0.0951}},
 {'year': 2019,
  'month': 12,
  'portfolio': ['300468'],
  'data': {'decision_weights': [0.7864, 0.2136],
   'performance': [0.0904, -0.0, 0.0, -0.0, 0.7483],
   'normalized_performance': [0.0904, -0.0, 0.0, -0.0, 0.7483],
   'reward': 0.0904}},
 {'year': 2019,
  'month': 12,
  'portfolio': ['300608'],
  'data': {'decision_weights': [0.6156, 0.3844],
   'performance': [0.0147, -0.0, 0.0, -0.0, 0.9611],
   'normalized_performance': [0.0147, -0.0, 0.0, -0.0, 0.9611],
   'reward': 0.0147}},
 {'year': 2019,
  'month': 12,
  'portfolio': ['603096'],
  'data': {'decision_weights': [0.1967, 0.8033],
   'performance': [0.0069, -0.0, 0.0, -0.0, 0.7153],
   'normalized_performance': [0.0069, -0.0, 0.0, -0.0, 0.7153],
   'reward': 0.0069}},
 {'year': 2019,
  'month': 12,
  'portfolio': ['002788'],
  'data': {'decision_weights': [0.2032, 0.7968],
   'performance': [0.0042, -0.0, 0.0, -0.0, 0.7282],
   'normalized_performance': [0.0042, -0.0, 0.0, -0.0, 0.7282],
   'reward': 0.0042}},
 {'year': 2019,
  'month': 12,
  'portfolio': ['603999'],
  'data': {'decision_weights': [1.0, 0.0],
   'performance': [0.0215, -0.0, 0.0, -0.0, -0.0],
   'normalized_performance': [0.0215, -0.0, 0.0, -0.0, -0.0],
   'reward': 0.0215}},
 {'year': 2019,
  'month': 12,
  'portfolio': ['002938'],
  'data': {'decision_weights': [1.0, 0.0],
   'performance': [0.1131, -0.0, 0.0, -0.0, -0.0],
   'normalized_performance': [0.1131, -0.0, 0.0, -0.0, -0.0],
   'reward': 0.1131}},
 {'year': 2019,
  'month': 12,
  'portfolio': ['688089'],
  'data': {'decision_weights': [0.4819, 0.5181],
   'performance': [0.0042, -0.0, 0.0, -0.0, 0.9991],
   'normalized_performance': [0.0042, -0.0, 0.0, -0.0, 0.9991],
   'reward': 0.0042}},
 {'year': 2019,
  'month': 12,
  'portfolio': ['002897'],
  'data': {'decision_weights': [0.5, 0.5],
   'performance': [0.0061, -0.0, 0.0, -0.0, 1.0],
   'normalized_performance': [0.0061, -0.0, 0.0, -0.0, 1.0],
   'reward': 0.0061}},
 {'year': 2019,
  'month': 12,
  'portfolio': ['002757'],
  'data': {'decision_weights': [0.6537, 0.3463],
   'performance': [0.0379, -0.0, 0.0, -0.0, 0.9307],
   'normalized_performance': [0.0379, -0.0, 0.0, -0.0, 0.9307],
   'reward': 0.0379}},
 {'year': 2019,
  'month': 12,
  'portfolio': ['603676'],
  'data': {'decision_weights': [0.5, 0.5],
   'performance': [0.0245, -0.0, 0.0, -0.0, 1.0],
   'normalized_performance': [0.0245, -0.0, 0.0, -0.0, 1.0],
   'reward': 0.0245}},
 {'year': 2019,
  'month': 12,
  'portfolio': ['688022'],
  'data': {'decision_weights': [1.0, 0.0],
   'performance': [0.332, -0.0, 0.0, -0.0, -0.0],
   'normalized_performance': [0.332, -0.0, 0.0, -0.0, -0.0],
   'reward': 0.332}},
 {'year': 2019,
  'month': 12,
  'portfolio': ['300662'],
  'data': {'decision_weights': [1.0, 0.0],
   'performance': [0.0649, -0.0, 0.0, -0.0, -0.0],
   'normalized_performance': [0.0649, -0.0, 0.0, -0.0, -0.0],
   'reward': 0.0649}},
 {'year': 2019,
  'month': 12,
  'portfolio': ['688366'],
  'data': {'decision_weights': [1.0, 0.0],
   'performance': [0.0967, -0.0, 0.0, -0.0, -0.0],
   'normalized_performance': [0.0967, -0.0, 0.0, -0.0, -0.0],
   'reward': 0.0967}},
 {'year': 2019,
  'month': 12,
  'portfolio': ['688108'],
  'data': {'decision_weights': [1.0, 0.0],
   'performance': [0.111, -0.0, 0.0, -0.0, -0.0],
   'normalized_performance': [0.111, -0.0, 0.0, -0.0, -0.0],
   'reward': 0.111}},
 {'year': 2019,
  'month': 12,
  'portfolio': ['300676'],
  'data': {'decision_weights': [0.6516, 0.3484],
   'performance': [0.1035, -0.0, 0.0, -0.0, 0.9326],
   'normalized_performance': [0.1035, -0.0, 0.0, -0.0, 0.9326],
   'reward': 0.1035}},
 {'year': 2019,
  'month': 12,
  'portfolio': ['300702'],
  'data': {'decision_weights': [0.4769, 0.5231],
   'performance': [0.0593, -0.0, 0.0, -0.0, 0.9985],
   'normalized_performance': [0.0593, -0.0, 0.0, -0.0, 0.9985],
   'reward': 0.0593}},
 {'year': 2019,
  'month': 12,
  'portfolio': ['300502'],
  'data': {'decision_weights': [1.0, 0.0],
   'performance': [0.2721, -0.0, 0.0, -0.0, -0.0],
   'normalized_performance': [0.2721, -0.0, 0.0, -0.0, -0.0],
   'reward': 0.2721}},
 {'year': 2019,
  'month': 12,
  'portfolio': ['300635'],
  'data': {'decision_weights': [1.0, 0.0],
   'performance': [0.0924, -0.0, 0.0, -0.0, -0.0],
   'normalized_performance': [0.0924, -0.0, 0.0, -0.0, -0.0],
   'reward': 0.0924}},
 {'year': 2019,
  'month': 12,
  'portfolio': ['300460'],
  'data': {'decision_weights': [0.5, 0.5],
   'performance': [0.1915, -0.0, 0.0, -0.0, 1.0],
   'normalized_performance': [0.1915, -0.0, 0.0, -0.0, 1.0],
   'reward': 0.1915}},
 {'year': 2019,
  'month': 12,
  'portfolio': ['300659'],
  'data': {'decision_weights': [0.5451, 0.4549],
   'performance': [0.1426, -0.0, 0.0, -0.0, 0.9941],
   'normalized_performance': [0.1426, -0.0, 0.0, -0.0, 0.9941],
   'reward': 0.1426}},
 {'year': 2019,
  'month': 12,
  'portfolio': ['002890'],
  'data': {'decision_weights': [1.0, 0.0],
   'performance': [0.05, -0.0, 0.0, -0.0, -0.0],
   'normalized_performance': [0.05, -0.0, 0.0, -0.0, -0.0],
   'reward': 0.05}},
 {'year': 2019,
  'month': 12,
  'portfolio': ['603717'],
  'data': {'decision_weights': [1.0, 0.0],
   'performance': [0.0034, -0.0, 0.0, -0.0, -0.0],
   'normalized_performance': [0.0034, -0.0, 0.0, -0.0, -0.0],
   'reward': 0.0034}},
 {'year': 2019,
  'month': 12,
  'portfolio': ['688118'],
  'data': {'decision_weights': [0.8008, 0.1992],
   'performance': [0.1052, -0.0, 0.0, -0.0, 0.7204],
   'normalized_performance': [0.1052, -0.0, 0.0, -0.0, 0.7204],
   'reward': 0.1052}},
 {'year': 2019,
  'month': 12,
  'portfolio': ['688020'],
  'data': {'decision_weights': [1.0, 0.0],
   'performance': [0.1298, -0.0, 0.0, -0.0, -0.0],
   'normalized_performance': [0.1298, -0.0, 0.0, -0.0, -0.0],
   'reward': 0.1298}},
 {'year': 2019,
  'month': 12,
  'portfolio': ['300587'],
  'data': {'decision_weights': [1.0, 0.0],
   'performance': [0.0392, -0.0, 0.0, -0.0, -0.0],
   'normalized_performance': [0.0392, -0.0, 0.0, -0.0, -0.0],
   'reward': 0.0392}},
 {'year': 2019,
  'month': 12,
  'portfolio': ['688139'],
  'data': {'decision_weights': [0.4621, 0.5379],
   'performance': [0.0526, -0.0, 0.0, -0.0, 0.9959],
   'normalized_performance': [0.0526, -0.0, 0.0, -0.0, 0.9959],
   'reward': 0.0526}},
 {'year': 2019,
  'month': 12,
  'portfolio': ['603297'],
  'data': {'decision_weights': [0.2566, 0.7434],
   'performance': [0.0047, -0.0, 0.0, -0.0, 0.8215],
   'normalized_performance': [0.0047, -0.0, 0.0, -0.0, 0.8215],
   'reward': 0.0047}},
 {'year': 2019,
  'month': 12,
  'portfolio': ['603326'],
  'data': {'decision_weights': [1.0, 0.0],
   'performance': [0.1453, -0.0, 0.0, -0.0, -0.0],
   'normalized_performance': [0.1453, -0.0, 0.0, -0.0, -0.0],
   'reward': 0.1453}},
 {'year': 2019,
  'month': 12,
  'portfolio': ['601086'],
  'data': {'decision_weights': [0.4336, 0.5664],
   'performance': [0.0051, -0.0, 0.0, -0.0, 0.9872],
   'normalized_performance': [0.0051, -0.0, 0.0, -0.0, 0.9872],
   'reward': 0.0051}},
 {'year': 2019,
  'month': 12,
  'portfolio': ['300418'],
  'data': {'decision_weights': [0.4194, 0.5806],
   'performance': [0.048, -0.0, 0.0, -0.0, 0.9812],
   'normalized_performance': [0.048, -0.0, 0.0, -0.0, 0.9812],
   'reward': 0.048}},
 {'year': 2019,
  'month': 12,
  'portfolio': ['603579'],
  'data': {'decision_weights': [1.0, 0.0],
   'performance': [0.0237, -0.0, 0.0, -0.0, -0.0],
   'normalized_performance': [0.0237, -0.0, 0.0, -0.0, -0.0],
   'reward': 0.0237}},
 {'year': 2019,
  'month': 12,
  'portfolio': ['300522'],
  'data': {'decision_weights': [0.2454, 0.7546],
   'performance': [0.0146, -0.0, 0.0, -0.0, 0.804],
   'normalized_performance': [0.0146, -0.0, 0.0, -0.0, 0.804],
   'reward': 0.0146}},
 {'year': 2019,
  'month': 12,
  'portfolio': ['300629'],
  'data': {'decision_weights': [0.5957, 0.4043],
   'performance': [0.155, -0.0, 0.0, -0.0, 0.9734],
   'normalized_performance': [0.155, -0.0, 0.0, -0.0, 0.9734],
   'reward': 0.155}},
 {'year': 2019,
  'month': 12,
  'portfolio': ['603666'],
  'data': {'decision_weights': [0.8035, 0.1965],
   'performance': [0.1772, -0.0, 0.0, -0.0, 0.7149],
   'normalized_performance': [0.1772, -0.0, 0.0, -0.0, 0.7149],
   'reward': 0.1772}},
 {'year': 2019,
  'month': 12,
  'portfolio': ['300724'],
  'data': {'decision_weights': [0.0281, 0.9719],
   'performance': [0.0127, -0.0, 0.0, -0.0, 0.1846],
   'normalized_performance': [0.0127, -0.0, 0.0, -0.0, 0.1846],
   'reward': 0.0127}},
 {'year': 2019,
  'month': 12,
  'portfolio': ['603022'],
  'data': {'decision_weights': [0.8032, 0.1968],
   'performance': [0.1334, -0.0, 0.0, -0.0, 0.7154],
   'normalized_performance': [0.1334, -0.0, 0.0, -0.0, 0.7154],
   'reward': 0.1334}},
 {'year': 2019,
  'month': 12,
  'portfolio': ['603118'],
  'data': {'decision_weights': [1.0, 0.0],
   'performance': [0.1386, -0.0, 0.0, -0.0, -0.0],
   'normalized_performance': [0.1386, -0.0, 0.0, -0.0, -0.0],
   'reward': 0.1386}},
 {'year': 2019,
  'month': 12,
  'portfolio': ['300541'],
  'data': {'decision_weights': [1.0, 0.0],
   'performance': [0.1024, -0.0, 0.0, -0.0, -0.0],
   'normalized_performance': [0.1024, -0.0, 0.0, -0.0, -0.0],
   'reward': 0.1024}},
 {'year': 2019,
  'month': 12,
  'portfolio': ['300514'],
  'data': {'decision_weights': [0.5833, 0.4167],
   'performance': [0.0092, -0.0, 0.0, -0.0, 0.9799],
   'normalized_performance': [0.0092, -0.0, 0.0, -0.0, 0.9799],
   'reward': 0.0092}},
 {'year': 2019,
  'month': 12,
  'portfolio': ['300696'],
  'data': {'decision_weights': [0.5392, 0.4608],
   'performance': [0.2008, -0.0, 0.0, -0.0, 0.9956],
   'normalized_performance': [0.2008, -0.0, 0.0, -0.0, 0.9956],
   'reward': 0.2008}},
 {'year': 2019,
  'month': 12,
  'portfolio': ['300617'],
  'data': {'decision_weights': [1.0, 0.0],
   'performance': [0.2892, -0.0, 0.0, -0.0, -0.0],
   'normalized_performance': [0.2892, -0.0, 0.0, -0.0, -0.0],
   'reward': 0.2892}},
 {'year': 2019,
  'month': 12,
  'portfolio': ['002838'],
  'data': {'decision_weights': [0.4478, 0.5522],
   'performance': [0.0336, -0.0, 0.0, -0.0, 0.9921],
   'normalized_performance': [0.0336, -0.0, 0.0, -0.0, 0.9921],
   'reward': 0.0336}},
 {'year': 2019,
  'month': 12,
  'portfolio': ['300672'],
  'data': {'decision_weights': [0.1585, 0.8415],
   'performance': [0.0696, -0.0, 0.0, -0.0, 0.6307],
   'normalized_performance': [0.0696, -0.0, 0.0, -0.0, 0.6307],
   'reward': 0.0696}},
 {'year': 2019,
  'month': 12,
  'portfolio': ['688123'],
  'data': {'decision_weights': [1.0, 0.0],
   'performance': [0.1195, -0.0, 0.0, -0.0, -0.0],
   'normalized_performance': [0.1195, -0.0, 0.0, -0.0, -0.0],
   'reward': 0.1195}},
 {'year': 2019,
  'month': 12,
  'portfolio': ['300494'],
  'data': {'decision_weights': [0.4931, 0.5069],
   'performance': [0.0113, -0.0, 0.0, -0.0, 0.9999],
   'normalized_performance': [0.0113, -0.0, 0.0, -0.0, 0.9999],
   'reward': 0.0113}},
 {'year': 2019,
  'month': 12,
  'portfolio': ['300785'],
  'data': {'decision_weights': [1.0, 0.0],
   'performance': [0.0901, -0.0, 0.0, -0.0, -0.0],
   'normalized_performance': [0.0901, -0.0, 0.0, -0.0, -0.0],
   'reward': 0.0901}},
 {'year': 2019,
  'month': 12,
  'portfolio': ['002846'],
  'data': {'decision_weights': [0.8931, 0.1069],
   'performance': [0.1013, -0.0, 0.0, -0.0, 0.4904],
   'normalized_performance': [0.1013, -0.0, 0.0, -0.0, 0.4904],
   'reward': 0.1013}},
 {'year': 2019,
  'month': 12,
  'portfolio': ['603232'],
  'data': {'decision_weights': [0.7153, 0.2847],
   'performance': [0.1775, -0.0, 0.0, -0.0, 0.8618],
   'normalized_performance': [0.1775, -0.0, 0.0, -0.0, 0.8618],
   'reward': 0.1775}},
 {'year': 2019,
  'month': 12,
  'portfolio': ['300721'],
  'data': {'decision_weights': [0.5, 0.5],
   'performance': [0.0577, -0.0, 0.0, -0.0, 1.0],
   'normalized_performance': [0.0577, -0.0, 0.0, -0.0, 1.0],
   'reward': 0.0577}},
 {'year': 2019,
  'month': 12,
  'portfolio': ['603679'],
  'data': {'decision_weights': [0.84, 0.16],
   'performance': [0.1121, -0.0, 0.0, -0.0, 0.6344],
   'normalized_performance': [0.1121, -0.0, 0.0, -0.0, 0.6344],
   'reward': 0.1121}},
 {'year': 2019,
  'month': 12,
  'portfolio': ['603505'],
  'data': {'decision_weights': [0.2564, 0.7436],
   'performance': [0.0437, -0.0, 0.0, -0.0, 0.8212],
   'normalized_performance': [0.0437, -0.0, 0.0, -0.0, 0.8212],
   'reward': 0.0437}},
 {'year': 2019,
  'month': 12,
  'portfolio': ['603600'],
  'data': {'decision_weights': [0.336, 0.664],
   'performance': [0.0282, -0.0, 0.0, -0.0, 0.921],
   'normalized_performance': [0.0282, -0.0, 0.0, -0.0, 0.921],
   'reward': 0.0282}},
 {'year': 2019,
  'month': 12,
  'portfolio': ['688138'],
  'data': {'decision_weights': [1.0, 0.0],
   'performance': [0.1889, -0.0, 0.0, -0.0, -0.0],
   'normalized_performance': [0.1889, -0.0, 0.0, -0.0, -0.0],
   'reward': 0.1889}},
 {'year': 2019,
  'month': 12,
  'portfolio': ['603587'],
  'data': {'decision_weights': [0.3632, 0.6368],
   'performance': [0.0024, -0.0, 0.0, -0.0, 0.9453],
   'normalized_performance': [0.0024, -0.0, 0.0, -0.0, 0.9453],
   'reward': 0.0024}},
 {'year': 2019,
  'month': 12,
  'portfolio': ['002837'],
  'data': {'decision_weights': [1.0, 0.0],
   'performance': [0.6771, -0.0, 0.0, -0.0, -0.0],
   'normalized_performance': [0.6771, -0.0, 0.0, -0.0, -0.0],
   'reward': 0.6771}},
 {'year': 2019,
  'month': 12,
  'portfolio': ['002902'],
  'data': {'decision_weights': [0.4464, 0.5536],
   'performance': [0.0017, -0.0, 0.0, -0.0, 0.9917],
   'normalized_performance': [0.0017, -0.0, 0.0, -0.0, 0.9917],
   'reward': 0.0017}},
 {'year': 2019,
  'month': 12,
  'portfolio': ['603520'],
  'data': {'decision_weights': [0.5805, 0.4195],
   'performance': [0.0586, -0.0, 0.0, -0.0, 0.9812],
   'normalized_performance': [0.0586, -0.0, 0.0, -0.0, 0.9812],
   'reward': 0.0586}},
 {'year': 2019,
  'month': 12,
  'portfolio': ['688012'],
  'data': {'decision_weights': [0.87, 0.13],
   'performance': [0.8525, -0.0, 0.0, -0.0, 0.5575],